//test
window.professors = [
  {
    name: "권동현",
    mbti: "ENTJ",
    image: "./prof_photo/kwondonghyun.jpg",
    prefs: {
      mbti: "ENTJ",
      lang: "C",
      food: "한식",
      classTime: "오전",
      classType: "이론",
      estimateType: "중간고사",
      schedule: "4연강",
      travel: "바다",
      os: "Windows",
      exam: "응용",
    },
  },
  {
    name: "김호원",
    mbti: "ENTJ",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745915866039100.jpg",
    prefs: {
      mbti: "ENTJ",
      lang: "Python Java",
      food: "한식 일식",
      classTime: "오전",
      classType: "실습",
      estimateType: "텀 프로젝트",
      schedule: "4연강",
      travel: "바다",
      os: "Windows Mac",
      exam: "응용",
    },
  },
  {
    name: "김원석",
    mbti: "INTJ",
    image: "./prof_photo/kimoneseok.png",
    prefs: {
      mbti: "INTJ",
      lang: "C# JavaScript", //일단 어케해야할지 몰라서 공란
      food: "중식",
      classTime: "오후",
      classType: "실습 이론",
      estimateType: "텀 프로젝트",
      schedule: "4연강",
      travel: "산",
      os: "Mac",
      exam: "암기",
    },
  },
  {
    name: "박진선",
    mbti: "ISTJ",
    image: "./prof_photo/parkjinsun.jpg",
    prefs: {
      mbti: "ISTJ",
      lang: "Python",
      food: "한식",
      classTime: "오후",
      classType: "이론",
      estimateType: "텀 프로젝트",
      schedule: "4연강",
      travel: "바다",
      os: "Windows",
      exam: "응용",
    },
  },
  {
    name: "박영진",
    mbti: "INTP",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745915942049100.jpg",
    prefs: {
      mbti: "INTP",
      lang: "C",
      food: "한식",
      classTime: "오후",
      classType: "실습",
      estimateType: "텀 프로젝트",
      schedule: "4연강",
      travel: "바다",
      os: "Windows",
      exam: "응용",
    },
  },
  {
    name: "송길태",
    mbti: "ENFJ",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745916106131100.jpeg",
    prefs: {
      mbti: "ENFJ",
      lang: "C",
      food: "한식",
      classTime: "오전",
      classType: "이론",
      estimateType: "중간고사",
      schedule: "4연강",
      travel: "바다",
      os: "Mac",
      exam: "응용",
    },
  },
  {
    name: "우균",
    mbti: "ESTJ",
    image:
      "./prof_photo/woogyun.png",
    prefs: {
      mbti: "ESTJ",
      lang: "C",
      food: "한식",
      classTime: "오전",
      classType: "실습",
      estimateType: "중간고사 텀 프로젝트",
      schedule: "우주공강",
      travel: "바다",
      os: "Windows Mac",
      exam: "응용",
    },
  },
  {
    name: "유영환",
    mbti: "INFP",
    image: "./prof_photo/yuyonghwan.jpg",
    prefs: {
      mbti: "INFP",
      lang: "C++",
      food: "한식",
      classTime: "오전",
      classType: "실습",
      estimateType: "텀 프로젝트 중간고사",
      schedule: "우주공강",
      travel: "산",
      os: "Windows",
      exam: "응용",
    },
  },
  {
    name: "이명호",
    mbti: "ENTP",
    image: "./prof_photo/leemyungho.jpg",
    prefs: {
      mbti: "ENTP",
      lang: "Python",
      food: "한식",
      classTime: "오후",
      classType: "실습",
      estimateType: "텀 프로젝트",
      schedule: "우주공강",
      travel: "바다",
      os: "Mac",
      exam: "응용",
    },
  },
  {
    name: "조준수",
    mbti: "ISTP",
    image: "./prof_photo/chojunsu.jpg",
    prefs: {
      mbti: "ISTP",
      lang: "Python",
      food: "일식",
      classTime: "오후",
      classType: "이론",
      estimateType: "텀 프로젝트",
      schedule: "우주공강",
      travel: "바다",
      os: "Windows",
      exam: "응용",
    },
  },
  {
    name: "최동희",
    mbti: "ENTP",
    image: "./prof_photo/choidonghee.jpg",
    prefs: {
      mbti: "ENTP",
      lang: "Python",
      food: "한식",
      classTime: "오전",
      classType: "실습",
      estimateType: "텀 프로젝트",
      schedule: "우주공강",
      travel: "바다",
      os: "Mac",
      exam: "응용",
    },
  },
];
