window.professors = [
  {
    name: "김원석",
    mbti: "ESFP",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745915760699100.jpg",
    prefs: {
      mbti: "ESFP",
      lang: "",
      food: "양식",
      classTime: "",
      classType: "",
      estimateType: "중간고사",
      schedule: "",
      travel: "",
      os: "Mac",
      exam: "",
    },
  },
  {
    name: "권동현",
    mbti: "ESFP",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745915670045100.jpg",
    prefs: {
      mbti: "ESFP",
      lang: "",
      food: "양식",
      classTime: "",
      classType: "",
      estimateType: "중간고사",
      schedule: "",
      travel: "",
      os: "Mac",
      exam: "",
    },
  },

  {
    name: "김정구",
    mbti: "",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745915780495100.jpg",
    prefs: {
      mbti: "",
      lang: "",
      food: "",
      classTime: "",
      classType: "",
      estimateType: "",
      schedule: "",
      travel: "",
      os: "",
      exam: "",
    },
  },
  {
    name: "박진선",
    mbti: "",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745915958018100.jpg",
    prefs: {
      mbti: "",
      lang: "",
      food: "",
      classTime: "",
      classType: "",
      estimateType: "",
      schedule: "",
      travel: "",
      os: "",
      exam: "",
    },
  },
  {
    name: "백윤주",
    mbti: "",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745916060779100.jpg",
    prefs: {
      mbti: "",
      lang: "",
      food: "",
      classTime: "",
      classType: "",
      estimateType: "",
      schedule: "",
      travel: "",
      os: "",
      exam: "",
    },
  },
  {
    name: "송길태",
    mbti: "",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745916106131100.jpeg",
    prefs: {
      mbti: "",
      lang: "",
      food: "",
      classTime: "",
      classType: "",
      estimateType: "",
      schedule: "",
      travel: "",
      os: "",
      exam: "",
    },
  },
  {
    name: "우균",
    mbti: "",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745916176742100.jpg",
    prefs: {
      mbti: "",
      lang: "",
      food: "",
      classTime: "",
      classType: "",
      estimateType: "",
      schedule: "",
      travel: "",
      os: "",
      exam: "",
    },
  },
  {
    name: "유영환",
    mbti: "",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745916193298100.jpg",
    prefs: {
      mbti: "",
      lang: "",
      food: "",
      classTime: "",
      classType: "",
      estimateType: "",
      schedule: "",
      travel: "",
      os: "",
      exam: "",
    },
  },
  {
    name: "전상률",
    mbti: "",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745916267579100.jpg",
    prefs: {
      mbti: "",
      lang: "",
      food: "",
      classTime: "",
      classType: "",
      estimateType: "",
      schedule: "",
      travel: "",
      os: "",
      exam: "",
    },
  },
  {
    name: "조준수",
    mbti: "ESFP",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745916308281100.jpg",
    prefs: {
      mbti: "ESFP",
      lang: "",
      food: "한식",
      classTime: "",
      classType: "",
      estimateType: "중간고사",
      schedule: "",
      travel: "",
      os: "windows",
      exam: "",
    },
  },
];
