window.professors = [
  {
    name: "박진선",
    mbti: "ISTJ",
    image:
      "./prof_photo/parkjinsun.jpg",
    prefs: {
      mbti: "ISTJ",
      lang: "Python",
      food: "한식",
      classTime: "오후",
      classType: "이론",
      estimateType: "텀 프로젝트",
      schedule: "4연강",
      travel: "바다",
      os: "Windows",
      exam: "응용",
    },
  },
   {
    name: "박영진",
    mbti: "INTP",
    image: "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745915942049100.jpg",
    prefs: {
      mbti: "INTP",
      lang: "C",
      food: "한식",
      classTime: "오후",
      classType: "실습",
      estimateType: "텀 프로젝트",
      schedule: "4연강",
      travel: "바다",
      os: "Windows",
      exam: "응용",
    },
  },
  {
    name: "송길태",
    mbti: "ENFJ",
    image:
      "https://cse.pusan.ac.kr/sites/cse/atchmnfl/proIntro/thumbnail/temp_1745916106131100.jpeg",
    prefs: {
      mbti: "ENFJ",
      lang: "C",
      food: "한식",
      classTime: "오전",
      classType: "이론",
      estimateType: "중간고사",
      schedule: "4연강",
      travel: "바다",
      os: "Mac",
      exam: "응용",
    },
  },
  {
    name: "이명호",
    mbti: "ENTP",
    image:
      "./prof_photo/leemyungho.jpg",
    prefs: {
      mbti: "ENTP",
      lang: "Python",
      food: "한식",
      classTime: "오후",
      classType: "실습",
      estimateType: "텀 프로젝트",
      schedule: "우주공강",
      travel: "바다",
      os: "Mac",
      exam: "응용",
    },
  },
  {
    name: "조준수",
    mbti: "ISTP",
    image: "./prof_photo/chojunsu.jpg",
    prefs: {
      mbti: "ISTP",
      lang: "Python",
      food: "일식",
      classTime: "오후",
      classType: "이론",
      estimateType: "텀 프로젝트",
      schedule: "우주공강",
      travel: "바다",
      os: "Windows",
      exam: "응용",
    },
  },
  {
    name: "최동희",
    mbti: "ENTP",
    image: "./prof_photo/choidonghee.jpg",
    prefs: {
      mbti: "ENTP",
      lang: "Python",
      food: "한식",
      classTime: "오전",
      classType: "실습",
      estimateType: "텀 프로젝트",
      schedule: "우주공강",
      travel: "바다",
      os: "Mac",
      exam: "응용",
    },
  },
];

